# Generated by Django 6.1.1 on 2026-09-28 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('target_object', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('event_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('nsqf_level', models.IntegerField(default=4)),
                ('nco_code', models.CharField(max_length=20)),
                ('duration_hours', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('labour_market_index', models.FloatField(default=0.75)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('central_ministry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_wage_monthly', models.IntegerField(default=14500)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('cin_or_gstin', models.CharField(max_length=30)),
                ('udyam_reg', models.CharField(blank=True, max_length=30)),
                ('sector', models.CharField(max_length=100)),
                ('trust_score', models.FloatField(default=0.88)),
                ('is_verified_badge', models.BooleanField(default=True)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('fraud_reason', models.CharField(blank=True, max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.state')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeEpisode',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('WAGE_EMPLOYMENT', 'Wage Employment'), ('SELF_EMPLOYMENT', 'Self Employment'), ('APPRENTICESHIP', 'Registered Apprenticeship'), ('HIGHER_EDUCATION', 'Further Education'), ('NOT_EMPLOYED', 'Not Employed'), ('UNKNOWN_UNREACHABLE', 'Unknown / Unreachable')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('nco_code', models.CharField(blank=True, max_length=20)),
                ('wage_band', models.CharField(choices=[('BELOW_MIN_WAGE', 'Below Minimum Wage'), ('1.0X_TO_1.5X', '1.0x to 1.5x Minimum Wage'), ('1.5X_TO_2.0X', '1.5x to 2.0x Minimum Wage'), ('ABOVE_2.0X', 'Above 2.0x Minimum Wage'), ('NOT_APPLICABLE', 'Not Applicable')], default='1.0X_TO_1.5X', max_length=30)),
                ('monthly_wage_inr', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('A', 'Tier A: Statutory Registry / Verified Document'), ('B', 'Tier B: Employer Confirmed / Provider Verified'), ('C', 'Tier C: Corroborated Self-Report'), ('D', 'Tier D: Unverified Self-Report'), ('U', 'Tier U: Unknown / Unreachable')], max_length=1)),
                ('tier_source', models.CharField(max_length=100)),
                ('rules_version', models.CharField(default='v2.0_NAT', max_length=20)),
                ('non_placement_reason', models.CharField(blank=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.district')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilltrace.employer')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EPFO_HASH_CONFIRMED', 'EPFO UAN / Contribution Hash Match'), ('EMPLOYER_3TAP_CONFIRMED', 'Direct Employer 3-Tap Web Verification'), ('SALARY_SLIP_VERIFIED', 'Salary Slip Bank Credit OCR Proof'), ('UDYAM_REGISTRATION', 'Udyam MSME Registration Certificate'), ('BANK_UPI_MERCHANT', 'UPI Merchant QR Transaction History'), ('APPRENTICE_PORTAL_CONTRACT', 'NAPS/NATS Active Apprenticeship Contract'), ('SELF_SURVEY_RESPONSE', 'Consented Micro-Survey Response')], max_length=40)),
                ('document_ref', models.CharField(max_length=100)),
                ('verified_by', models.CharField(max_length=100)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='skilltrace.outcomeepisode')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('stid', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('state_code_first', models.CharField(db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MERGED', 'Merged'), ('FLAGGED', 'Flagged'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_records', to='skilltrace.person')),
            ],
        ),
        migrations.AddField(
            model_name='outcomeepisode',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_episodes', to='skilltrace.person'),
        ),
        migrations.CreateModel(
            name='IdentityMatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('match_reasons', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Human Review'), ('MERGED', 'Resolved: Merged as Same Person'), ('REJECTED_DISTINCT', 'Resolved: Distinct Persons')], default='PENDING_REVIEW', max_length=30)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates_a', to='skilltrace.person')),
                ('candidate_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates_b', to='skilltrace.person')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('wave', models.CharField(choices=[('T+30', 'T+30 Days Post-Certification'), ('T+90', 'T+90 Days Post-Certification'), ('T+180', 'T+180 Days Post-Certification'), ('T+365', 'T+365 Days Post-Certification'), ('T+730', 'T+730 Days Post-Certification')], max_length=10)),
                ('due_date', models.DateField()),
                ('channel_current', models.CharField(choices=[('TELEGRAM', 'Telegram Automated Bot'), ('WHATSAPP', 'WhatsApp Cloud API Micro-Survey'), ('SMS_LINK', 'SMS Short Link Interactive Form'), ('IVR_CALL', 'Voice IVR / Missed Call System'), ('ASSISTED_CALL', 'Assisted Call Workbench (Field Agent)'), ('FIELD_VISIT', 'Physical In-Person Verification')], default='TELEGRAM', max_length=20)),
                ('escalation_step', models.IntegerField(default=1)),
                ('attempts_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Dispatched'), ('ANSWERED', 'Answered / Completed'), ('NO_RESPONSE', 'No Response'), ('ESCALATED', 'Escalated to Next Channel'), ('UNREACHABLE', 'Marked Unreachable')], default='SCHEDULED', max_length=20)),
                ('response_propensity_score', models.FloatField(default=0.72)),
                ('intensive_subsample', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='skilltrace.person')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('MOBILE', 'Mobile Phone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('GUARDIAN_MOBILE', 'Guardian Mobile')], max_length=20)),
                ('value_masked', models.CharField(max_length=50)),
                ('value_hash', models.CharField(db_index=True, max_length=64)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('last_seen_date', models.DateField(auto_now=True)),
                ('churn_count', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='skilltrace.person')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentArtefact',
            fields=[
                ('artefact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_version', models.CharField(default='v2.1-DPDP2023', max_length=20)),
                ('language', models.CharField(default='HIN', max_length=10)),
                ('channel', models.CharField(choices=[('MOBILE_OTP', 'Mobile OTP'), ('E_SIGN', 'e-Sign / DigiLocker'), ('BIOMETRIC', 'Biometric Authentication'), ('VOICE_CONSENT', 'Voice Assisted Consent')], max_length=30)),
                ('purpose_flags', models.JSONField(default=dict)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='skilltrace.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('TRANSGENDER', 'Transgender')], max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('address_line', models.TextField()),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('phone_last4', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=20)),
                ('disability', models.BooleanField(default=False)),
                ('urban_rural', models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural')], max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pii', to='skilltrace.person')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('accreditation_grade', models.CharField(default='A', max_length=10)),
                ('geo_lat', models.FloatField(default=19.076)),
                ('geo_lng', models.FloatField(default=72.8777)),
                ('risk_score', models.FloatField(default=0.08)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.state')),
            ],
        ),
        migrations.AddField(
            model_name='outcomeepisode',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='skilltrace.state'),
        ),
        migrations.CreateModel(
            name='ActionCase',
            fields=[
                ('case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical Action Required'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Informational Advisory')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'Investigation In Progress'), ('REMEDIATED', 'Corrective Action Applied'), ('CLOSED_WITH_EVIDENCE', 'Closed with Audit Evidence')], default='OPEN', max_length=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('corrective_action_log', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilltrace.course')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.district')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilltrace.provider')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.state')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('employment_status', models.CharField(max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('wage_reported', models.IntegerField(default=0)),
                ('non_placement_reason_raw', models.TextField(blank=True)),
                ('reason_nlp_classified', models.CharField(blank=True, max_length=100)),
                ('disposition_code', models.CharField(choices=[('COMPLETE', 'Survey Complete'), ('CALL_BACK_LATER', 'Callback Requested'), ('WRONG_NUMBER', 'Wrong Number / Changed SIM'), ('REFUSED', 'Refused Response'), ('DECEASED', 'Deceased'), ('LANGUAGE_BARRIER', 'Regional Language Barrier')], default='COMPLETE', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='skilltrace.followuptask')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('is_currently_employed', models.BooleanField(blank=True, null=True)),
                ('confirmed_start_date', models.DateField(blank=True, null=True)),
                ('confirmed_wage_band', models.CharField(blank=True, max_length=30)),
                ('skill_rating', models.IntegerField(blank=True, null=True)),
                ('response_ip_hash', models.CharField(blank=True, max_length=64)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='skilltrace.employer')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilltrace.outcomeepisode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.person')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_trainee_id', models.CharField(max_length=60)),
                ('enrolled_date', models.DateField()),
                ('certified_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosswalks', to='skilltrace.person')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.provider')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrace.scheme')),
            ],
            options={
                'unique_together': {('scheme', 'scheme_trainee_id')},
            },
        ),
    ]
