# Generated by Django 6.1.1 on 2026-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_whatsapp_outreach',
            field=models.BooleanField(default=True, help_text='Permission for automated WhatsApp milestone pings'),
        ),
        migrations.AddField(
            model_name='user',
            name='alt_phone',
            field=models.CharField(blank=True, default='', help_text='Secondary/Alternative phone to prevent contact drift', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='area_type',
            field=models.CharField(choices=[('rural', 'Rural'), ('semi_urban', 'Semi-Urban'), ('urban', 'Urban')], default='urban', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_given',
            field=models.BooleanField(default=True, help_text='Consent for longitudinal livelihood tracking'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', help_text='Family/Village contact for assisted outreach', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pwd',
            field=models.BooleanField(default=False, help_text='Person with Disability (Divyangjan)'),
        ),
        migrations.AddField(
            model_name='user',
            name='trainee_id',
            field=models.CharField(blank=True, default='', help_text='Skill India Digital (SIDH) / APAAR Identifier', max_length=50),
        ),
    ]
