# Generated by Django 6.1.1 on 2026-09-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('employed', 'Formally Employed'), ('unemployed', 'Seeking Employment / Unemployed'), ('internship', 'Active Internship'), ('freelancing', 'Freelancing / Gig Economy'), ('self_employed', 'Self-Employed / Entrepreneur'), ('higher_studies', 'Higher Education / Studies')], default='unemployed', max_length=30)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('job_role', models.CharField(blank=True, default='', max_length=150)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contractual'), ('intern', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=30)),
                ('skills_used', models.CharField(blank=True, default='', help_text='Skills applied in current role', max_length=300)),
                ('is_verified_by_admin', models.BooleanField(default=False, help_text='Whether employment status was verified via offer letter or audit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
