# Generated by Django 6.1.1 on 2026-09-30 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrecord',
            name='current_monthly_wage',
            field=models.PositiveIntegerField(blank=True, help_text='Current monthly take-home salary in ₹', null=True),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='employer_gstin',
            field=models.CharField(blank=True, default='', help_text='Employer GSTIN', max_length=30),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='epfo_uan',
            field=models.CharField(blank=True, default='', help_text='Masked EPFO UAN or Social Security Signal', max_length=30),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='last_milestone_month',
            field=models.IntegerField(default=0, help_text='Latest completed milestone (0, 3, 6, 12, 24 mo)'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='training_relevance',
            field=models.CharField(choices=[('high', 'Directly Relevant (Daily Application)'), ('partial', 'Partially Relevant (Some Concepts Used)'), ('low', 'Minimally Relevant'), ('none', 'Not Relevant At All (Different Domain)')], default='high', max_length=20),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time Permanent'), ('part_time', 'Part-time'), ('contract', 'Contractual / Fixed-Term'), ('intern', 'Apprenticeship / Intern'), ('freelance', 'Self-Employed / Freelance')], default='full_time', max_length=30),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False, help_text='Whether verified via employer token or administrative audit'),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='status',
            field=models.CharField(choices=[('employed', 'Formally Employed'), ('unemployed', 'Seeking Employment / Unemployed'), ('internship', 'Active Internship / Apprenticeship (NAPS)'), ('freelancing', 'Freelancing / Gig Economy'), ('self_employed', 'Self-Employed / Micro-Entrepreneur'), ('higher_studies', 'Higher Education / Studies'), ('dropped_out', 'Inactive / Exited Labor Market')], default='unemployed', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('employer_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('employer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('employer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Employer Review'), ('confirmed', 'Verified & Confirmed'), ('disputed', 'Disputed by Employer'), ('expired', 'Link Expired')], default='pending', max_length=20)),
                ('confirmed_role', models.CharField(blank=True, default='', max_length=150)),
                ('confirmed_monthly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_joining_date', models.DateField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, default='', help_text='Employer GSTIN', max_length=30)),
                ('has_epfo_coverage', models.BooleanField(default=False, help_text='Candidate covered under EPFO/ESIC')),
                ('feedback_on_trainee', models.TextField(blank=True, default='', help_text='Manager feedback on skill readiness')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp_bot', 'Automated WhatsApp Conversational Bot'), ('ivr_voice', 'Automated Interactive Voice Response (IVR)'), ('sms_link', 'Tokenized 1-Click SMS Link'), ('assisted_call', 'Rozgar Sahayak (Tele-Calling Mobilizer)'), ('field_visit', 'Physical Centre / Field Mobilizer Visit')], max_length=30)),
                ('contact_number_used', models.CharField(max_length=20)),
                ('contact_type', models.CharField(choices=[('primary', 'Primary Mobile'), ('alt', 'Alternative Mobile'), ('guardian', 'Guardian / Village Relative Contact')], default='primary', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Queued for Dispatch'), ('delivered', 'Delivered / Awaiting Response'), ('responded', 'Response Received'), ('unreachable', 'Switched Off / Out of Coverage'), ('wrong_number', 'Wrong Number / SIM Changed'), ('escalated', 'Escalated to Alternative Contact')], default='delivered', max_length=30)),
                ('response_text', models.TextField(blank=True, default='')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_next_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='NonPlacementReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('relocation_refusal', 'Reluctance to Migrate Away from Home District'), ('wage_dissatisfaction', 'Offered Wage Inadequate for Urban Living Costs'), ('family_marriage', 'Caregiving / Family Opposition / Marriage Constraints'), ('skill_mismatch', 'Skill Gap / Failed Practical Employer Evaluation'), ('local_opportunity_lack', 'Absence of Relevant Industrial Clusters Locally'), ('health_personal', 'Medical or Personal Emergency'), ('joined_informal', 'Opted for Traditional / Unorganized Daily Wage'), ('higher_education', 'Enrolled in Full-Time Higher Degree'), ('other', 'Other Reason')], max_length=40)),
                ('details', models.TextField(help_text='Context shared by candidate or mobilizer')),
                ('recommended_action', models.TextField(blank=True, default='', help_text='Suggested intervention (e.g. Local apprenticeship, stipend, relocation grant)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_reasons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LongitudinalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_month', models.IntegerField(choices=[(0, 'Month 0 (Placement / Initial Exit)'), (3, 'Month 3 (Early Retention Check)'), (6, 'Month 6 (Mid-Term Retention Check)'), (12, 'Month 12 (1-Year Sustained Livelihood)'), (24, 'Month 24 (Long-Term Economic Mobility)')])),
                ('status', models.CharField(choices=[('employed', 'Formally Employed'), ('unemployed', 'Seeking Employment / Unemployed'), ('internship', 'Active Internship / Apprenticeship (NAPS)'), ('freelancing', 'Freelancing / Gig Economy'), ('self_employed', 'Self-Employed / Micro-Entrepreneur'), ('higher_studies', 'Higher Education / Studies'), ('dropped_out', 'Inactive / Exited Labor Market')], max_length=30)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('job_role', models.CharField(blank=True, default='', max_length=150)),
                ('monthly_wage', models.PositiveIntegerField(default=0, help_text='Actual monthly take-home in ₹')),
                ('is_retained', models.BooleanField(default=True, help_text='Active in formal or productive livelihood')),
                ('is_wage_increased', models.BooleanField(default=False, help_text='Wage increased compared to earlier milestone')),
                ('training_relevance', models.CharField(choices=[('high', 'Directly Relevant (Daily Application)'), ('partial', 'Partially Relevant (Some Concepts Used)'), ('low', 'Minimally Relevant'), ('none', 'Not Relevant At All (Different Domain)')], default='high', max_length=20)),
                ('verification_source', models.CharField(choices=[('self_reported', 'Trainee WhatsApp/SMS Quick Response'), ('employer_confirmed', 'Employer 1-Click Token Confirmation'), ('assisted_call', 'Rozgar Sahayak / Call Center Outbound'), ('epfo_signal', 'EPFO / Bank Remittance Signal')], default='self_reported', max_length=30)),
                ('check_in_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longitudinal_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'milestone_month'],
                'unique_together': {('user', 'milestone_month')},
            },
        ),
    ]
