# Generated by Django 6.1.1 on 2026-09-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('tech', 'Technical / Programming'), ('data', 'Data & Analytics'), ('design', 'UI/UX & Design'), ('soft', 'Soft Skills & Leadership'), ('tools', 'Tools & Platforms')], default='tech', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(default='fa-solid fa-code', help_text='Font Awesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_score', models.FloatField(default=0.0, help_text='Aggregated verified score 0-100')),
                ('verified_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('mcq_score', models.FloatField(default=0.0)),
                ('practical_score', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
                ('viva_score', models.FloatField(default=0.0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_verified', '-verified_score', 'skill__name'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
