# Generated by Django 6.1.1 on 2026-09-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=3)),
                ('description', models.TextField()),
                ('provider', models.CharField(default='SkillBridge Learning', max_length=150)),
                ('duration', models.CharField(default='4 Weeks (20 Hours)', max_length=100)),
                ('url', models.URLField(blank=True, default='https://example.com/course', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_courses', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('score_before', models.FloatField(blank=True, help_text='Skill score before enrolling', null=True)),
                ('score_after', models.FloatField(blank=True, help_text='Skill score after completion re-assessment', null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
