# Generated by Django 6.1.1 on 2026-09-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nsdc_partner_code', models.CharField(help_text='SMART / NSDC Partner ID', max_length=50, unique=True)),
                ('accreditation_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('scheme_name', models.CharField(choices=[('pmkvy4', 'PMKVY 4.0 (Skill India)'), ('ddu_gky', 'DDU-GKY (Rural Development)'), ('vishwakarma', 'PM-Vishwakarma Scheme'), ('naps', 'National Apprenticeship Promotion (NAPS)'), ('state_mission', 'State Skill Development Mission (SSDM)'), ('csr_initiative', 'Corporate CSR Skilling Program')], default='pmkvy4', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='training.trainingcourse')),
            ],
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='training.cohort'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_aspirational', models.BooleanField(default=False, help_text='NITI Aayog Aspirational District')),
            ],
            options={
                'ordering': ['state', 'name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='training.district'),
        ),
        migrations.CreateModel(
            name='TrainingCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=200)),
                ('center_code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_centres', to='training.district')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='training.trainingprovider')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='training_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='training.trainingcentre'),
        ),
    ]
